-- 운동 카탈로그 시드 (재실행해도 title 중복은 무시)
-- craving_min/max: 이 운동이 적합한 흡연 욕구 강도(0~10). contraindications: 해당 건강 주의사항이 있으면 제외
INSERT INTO exercises
 (title, category, duration_minutes, intensity, target_symptoms, min_fitness_level, location, requires_equipment, contraindications, craving_min, craving_max, tags, description, instructions)
VALUES
('4-7-8 호흡', 'BREATHING', 3, 'LOW', '{CRAVING,ANXIETY,STRESS,INSOMNIA}', 'BEGINNER', 'ANY', FALSE, '{}', 0, 10, '{QUICK_RELIEF,CALMING}',
 '느린 호흡으로 부교감신경을 활성화해 욕구와 불안을 가라앉힙니다.',
 '4초 코로 들이마시기 → 7초 멈추기 → 8초 입으로 천천히 내쉬기. 4회 반복.'),
('박스 호흡', 'BREATHING', 3, 'LOW', '{CRAVING,ANXIETY,IRRITABILITY,STRESS}', 'BEGINNER', 'ANY', FALSE, '{}', 3, 10, '{QUICK_RELIEF,CALMING}',
 '같은 길이로 들이쉬고 멈추고 내쉬며 흥분 상태를 진정시킵니다.',
 '4초 들이마시기 → 4초 멈추기 → 4초 내쉬기 → 4초 멈추기. 6회 반복.'),
('복식호흡 5분', 'BREATHING', 5, 'LOW', '{CRAVING,STRESS,COUGH,FATIGUE}', 'BEGINNER', 'ANY', FALSE, '{}', 0, 6, '{CALMING,LUNG_CARE}',
 '배로 깊게 숨 쉬어 폐 용량 회복과 이완을 돕습니다.',
 '편하게 앉아 한 손을 배에 얹고, 배가 부풀도록 코로 들이마시고 천천히 내쉽니다.'),
('입술 오므림 호흡', 'BREATHING', 4, 'LOW', '{COUGH,ANXIETY,CRAVING}', 'BEGINNER', 'ANY', FALSE, '{}', 0, 7, '{LUNG_CARE,CALMING}',
 '날숨을 길게 해 기도 저항을 줄이고 숨 가쁨을 완화합니다.',
 '코로 2초 들이마시고, 입술을 모아 4초 이상 천천히 내쉽니다. 10회 반복.'),
('목·어깨 스트레칭', 'STRETCHING', 5, 'LOW', '{STRESS,IRRITABILITY,FATIGUE,CRAVING}', 'BEGINNER', 'INDOOR', FALSE, '{}', 0, 8, '{DESK_FRIENDLY,RELAXING}',
 '긴장한 목과 어깨를 풀어 짜증과 긴장을 낮춥니다.',
 '목을 좌우로 15초씩 기울이고, 어깨를 앞뒤로 10회 돌린 뒤 양팔을 머리 위로 깍지 끼고 늘입니다.'),
('전신 스트레칭 10분', 'STRETCHING', 10, 'LOW', '{STRESS,FATIGUE,RESTLESSNESS,INSOMNIA}', 'BEGINNER', 'INDOOR', FALSE, '{BACK_PAIN}', 0, 6, '{RELAXING,EVENING}',
 '몸 전체를 천천히 늘려 피로와 불안정한 느낌을 풀어줍니다.',
 '목→어깨→팔→허리→다리 순서로 각 부위 30초씩 늘려줍니다. 통증이 느껴지면 즉시 중단.'),
('자기 전 이완 스트레칭', 'STRETCHING', 8, 'LOW', '{INSOMNIA,STRESS,RESTLESSNESS}', 'BEGINNER', 'INDOOR', FALSE, '{}', 0, 6, '{EVENING,RELAXING}',
 '수면 전 근육 긴장을 풀어 금연 중 수면 문제를 줄입니다.',
 '침대 위에서 고양이 자세, 아기 자세, 누워서 무릎 안기를 각 1분씩 진행합니다.'),
('가벼운 걷기 10분', 'WALKING', 10, 'LOW', '{CRAVING,STRESS,FATIGUE,IRRITABILITY,ANXIETY}', 'BEGINNER', 'ANY', FALSE, '{}', 3, 10, '{QUICK_RELIEF,OUTDOOR_FRIENDLY}',
 '자리를 벗어나 걷는 것만으로도 흡연 욕구가 크게 줄어듭니다.',
 '편한 속도로 10분 걷습니다. 욕구가 강하면 주변을 한 바퀴 돌고 물을 마시세요.'),
('빠르게 걷기 20분', 'WALKING', 20, 'MEDIUM', '{STRESS,IRRITABILITY,FATIGUE,CRAVING}', 'BEGINNER', 'OUTDOOR', FALSE, '{HEART_CONDITION}', 2, 8, '{HABIT_BUILDING,OUTDOOR_FRIENDLY}',
 '약간 숨이 찰 정도의 걷기로 기분 개선과 체력 회복을 돕습니다.',
 '대화는 가능하지만 노래는 어려운 속도로 20분 걷습니다.'),
('실내 제자리 걷기', 'WALKING', 7, 'LOW', '{CRAVING,RESTLESSNESS,STRESS}', 'BEGINNER', 'INDOOR', FALSE, '{}', 3, 10, '{QUICK_RELIEF,INDOOR_FRIENDLY}',
 '밖에 나갈 수 없을 때 바로 할 수 있는 욕구 분산 운동입니다.',
 '무릎을 적당히 들어 올리며 7분간 제자리 걷기. 팔도 크게 흔듭니다.'),
('계단 오르기 5분', 'CARDIO', 5, 'MEDIUM', '{CRAVING,IRRITABILITY,RESTLESSNESS}', 'BEGINNER', 'INDOOR', FALSE, '{HEART_CONDITION,JOINT_PAIN,PREGNANCY}', 5, 10, '{QUICK_RELIEF}',
 '짧고 강한 활동으로 강한 흡연 욕구를 즉시 다른 곳으로 돌립니다.',
 '무리하지 않는 속도로 5분간 계단을 오르내립니다. 어지러우면 중단.'),
('제자리 가볍게 뛰기', 'CARDIO', 5, 'MEDIUM', '{CRAVING,IRRITABILITY,RESTLESSNESS,STRESS}', 'INTERMEDIATE', 'INDOOR', FALSE, '{HEART_CONDITION,HYPERTENSION,JOINT_PAIN,PREGNANCY,ASTHMA}', 6, 10, '{QUICK_RELIEF}',
 '심박을 빠르게 올려 강한 욕구를 이겨내는 데 도움을 줍니다.',
 '30초 가볍게 뛰기 + 30초 걷기를 5세트 반복합니다.'),
('조깅 20분', 'CARDIO', 20, 'MEDIUM', '{STRESS,IRRITABILITY,FATIGUE,CRAVING}', 'INTERMEDIATE', 'OUTDOOR', FALSE, '{HEART_CONDITION,HYPERTENSION,JOINT_PAIN,PREGNANCY,ASTHMA}', 2, 8, '{HABIT_BUILDING,OUTDOOR_FRIENDLY}',
 '꾸준한 유산소로 폐 기능 회복과 스트레스 해소를 돕습니다.',
 '5분 걷기로 워밍업 → 10분 가볍게 조깅 → 5분 걷기로 정리.'),
('인터벌 러닝 15분', 'CARDIO', 15, 'HIGH', '{STRESS,IRRITABILITY,RESTLESSNESS}', 'ADVANCED', 'OUTDOOR', FALSE, '{HEART_CONDITION,HYPERTENSION,JOINT_PAIN,PREGNANCY,ASTHMA}', 5, 10, '{HABIT_BUILDING}',
 '고강도 구간으로 쌓인 긴장과 짜증을 강하게 해소합니다.',
 '1분 빠르게 + 1분 천천히 × 6세트, 앞뒤 3분 걷기.'),
('줄넘기 10분', 'CARDIO', 10, 'HIGH', '{CRAVING,IRRITABILITY,RESTLESSNESS}', 'INTERMEDIATE', 'ANY', TRUE, '{HEART_CONDITION,HYPERTENSION,JOINT_PAIN,PREGNANCY}', 6, 10, '{QUICK_RELIEF}',
 '짧은 시간에 높은 강도로 욕구를 몰아냅니다.',
 '1분 뛰고 30초 쉬기를 7세트 반복합니다.'),
('맨몸 스쿼트 + 팔굽혀펴기', 'STRENGTH', 10, 'MEDIUM', '{CRAVING,IRRITABILITY,STRESS,RESTLESSNESS}', 'INTERMEDIATE', 'INDOOR', FALSE, '{HEART_CONDITION,HYPERTENSION,JOINT_PAIN,BACK_PAIN,PREGNANCY}', 4, 10, '{QUICK_RELIEF,HABIT_BUILDING}',
 '근력 운동에 집중하면 욕구에서 주의를 돌릴 수 있습니다.',
 '스쿼트 15회 + 무릎 팔굽혀펴기 10회 × 3세트, 세트 간 휴식 30초.'),
('벽 밀기·플랭크 코어', 'STRENGTH', 6, 'MEDIUM', '{CRAVING,STRESS,RESTLESSNESS}', 'BEGINNER', 'INDOOR', FALSE, '{BACK_PAIN,PREGNANCY}', 3, 9, '{QUICK_RELIEF}',
 '짧은 정적 근력 운동으로 몸에 집중하게 합니다.',
 '벽 밀기 30초 → 무릎 플랭크 20초 × 4세트.'),
('요가 기본 시퀀스', 'YOGA', 15, 'LOW', '{STRESS,ANXIETY,INSOMNIA,IRRITABILITY,FATIGUE}', 'BEGINNER', 'INDOOR', FALSE, '{PREGNANCY}', 0, 7, '{RELAXING,HABIT_BUILDING}',
 '호흡과 동작을 맞춰 몸과 마음의 긴장을 풀어줍니다.',
 '고양이-소 자세 → 다운독 → 전사 자세 → 아기 자세를 호흡에 맞춰 천천히.'),
('수면 요가', 'YOGA', 10, 'LOW', '{INSOMNIA,ANXIETY,STRESS}', 'BEGINNER', 'INDOOR', FALSE, '{}', 0, 6, '{EVENING,RELAXING}',
 '잠들기 전 가벼운 요가로 금연 중 불면을 완화합니다.',
 '다리 벽에 올리기 → 누워서 비틀기 → 송장 자세 3분.'),
('점진적 근육 이완', 'MINDFULNESS', 8, 'LOW', '{ANXIETY,STRESS,INSOMNIA,IRRITABILITY,CRAVING}', 'BEGINNER', 'INDOOR', FALSE, '{}', 0, 8, '{CALMING,EVENING}',
 '근육을 차례로 조였다 풀며 긴장을 낮춥니다.',
 '발끝부터 얼굴까지 부위별로 5초 힘주고 10초 이완.'),
('5-4-3-2-1 감각 집중', 'MINDFULNESS', 3, 'LOW', '{CRAVING,ANXIETY,STRESS}', 'BEGINNER', 'ANY', FALSE, '{}', 4, 10, '{QUICK_RELIEF,CALMING}',
 '주변 감각에 집중해 갑작스러운 욕구의 파도를 넘깁니다.',
 '보이는 것 5, 만져지는 것 4, 들리는 것 3, 냄새 2, 맛 1가지를 차례로 찾아봅니다.'),
('욕구 서핑 명상', 'MINDFULNESS', 5, 'LOW', '{CRAVING,IRRITABILITY}', 'BEGINNER', 'ANY', FALSE, '{}', 5, 10, '{QUICK_RELIEF,CALMING}',
 '욕구를 억누르지 않고 파도처럼 지나가게 두는 연습입니다.',
 '욕구가 몸 어디에서 느껴지는지 관찰하며 호흡. 보통 3~5분 안에 정점이 지나갑니다.'),
('가벼운 댄스', 'CARDIO', 10, 'MEDIUM', '{STRESS,IRRITABILITY,FATIGUE,RESTLESSNESS}', 'BEGINNER', 'INDOOR', FALSE, '{HEART_CONDITION,JOINT_PAIN,PREGNANCY}', 3, 9, '{HABIT_BUILDING,INDOOR_FRIENDLY}',
 '좋아하는 음악에 맞춰 움직이며 기분을 전환합니다.',
 '좋아하는 노래 3곡 동안 자유롭게 움직입니다.'),
('수건 어깨·가슴 열기', 'STRETCHING', 4, 'LOW', '{COUGH,STRESS,FATIGUE}', 'BEGINNER', 'INDOOR', TRUE, '{}', 0, 6, '{LUNG_CARE,DESK_FRIENDLY}',
 '가슴을 열어 호흡 공간을 넓히고 기침 불편을 줄입니다.',
 '수건을 양손으로 잡고 머리 위로 올려 뒤로 천천히 넘깁니다. 10회.')
ON CONFLICT (title) DO NOTHING;
